# -*- coding: utf-8 -*-
"""HRsyndata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-bXEtP_c2xjDEdX40MiyI48hk8eODVE
"""

import numpy as np
import pandas as pd

np.random.seed(42)
data_size = 1000

heart_rate = np.random.randint(35, 200, data_size)
spo2 = []
temperature = []

for hr in heart_rate:
    # SpO2 correlation
    if hr > 110:
        spo2.append(np.random.randint(88, 95))
    else:
        spo2.append(np.random.randint(94, 100))

    # Temperature correlation
    if hr > 110:
        temperature.append(np.random.uniform(37.5, 40.0))
    else:
        temperature.append(np.random.uniform(36.0, 37.4))

def label_risk(hr, spo2, temp):
    risk = 0
    if hr > 120 or hr < 50:
        risk += 1
    if spo2 < 90:
        risk += 1
    if temp > 39:
        risk += 1
    return 1 if risk >= 2 else 0

risk_label = [
    label_risk(hr, o2, temp)
    for hr, o2, temp in zip(heart_rate, spo2, temperature)
]

df = pd.DataFrame({
    "heart_rate": heart_rate,
    "spo2": spo2,
    "temperature": temperature,
    "risk_label" : risk_label

})

df.head()

df.to_csv("wearable_heart_risk_data.csv", index=False)



from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv("wearable_heart_risk_data.csv")
df.head()

X = df[["heart_rate", "spo2", "temperature"]]
y = df["risk_label"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

sample = np.array([[135, 89, 38.8]])  # HR, SpO2, Temp

risk_probability = model.predict_proba(sample)[0][1]
risk_percentage = risk_probability * 100

print(f"Cardiac Risk: {risk_percentage:.2f}%")

def risk_level(risk_percentage):
    if risk_percentage < 30:
        return "LOW"
    elif risk_percentage < 60:
        return "MEDIUM"
    else:
        return "HIGH"

def possible_conditions(hr, spo2, temp, risk_percentage):
    conditions = []

    if risk_percentage > 75:
        if hr > 160 or hr < 40:
            conditions.append("Severe Arrhythmia / Cardiac Arrest Risk")
        if spo2 < 90:
            conditions.append("Possible Acute Cardiac Event")

    if 60 <= risk_percentage <= 75:
        if hr > 120:
            conditions.append("Heart Attack (Myocardial Ischemia) Risk")
        if spo2 < 92:
            conditions.append("Oxygen Deprivation / Cardiac Stress")

    if 30 <= risk_percentage < 60:
        if hr > 100:
            conditions.append("Angina Pectoris / Cardiac Strain")

    if not conditions:
        conditions.append("No immediate cardiac condition detected")

    return conditions

hr = 145
spo2 = 89
temp = 38.9

sample = np.array([[hr, spo2, temp]])
risk_percentage = model.predict_proba(sample)[0][1] * 100

print("Cardiac Risk:", f"{risk_percentage:.2f}%")
print("Risk Level:", risk_level(risk_percentage))
print("Possible Conditions:")
for c in possible_conditions(hr, spo2, temp, risk_percentage):
    print("-", c)